### ISSUE TITLE
Suggestion: Change title color

### ISSUE THREAD

**Issue by TakuyaArai6I20VV** [TakuyaArai6I20VV/github-crash-course#1]
I think it would look better if the paragraph  in the section were a bit more gray.

The styling rule could be changed like this:

```css
section {
  color: rgb(173, 173, 173);
}
```
